=== Letractively/kitcampusguide/branches/BA_Miclaus/poimanager/WebContent/data/POIList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:kcg="http://www.cm-tm.uni-karlsruhe.de/KCG" targetNamespace="http://www.cm-tm.uni-karlsruhe.de/KCG"
	elementFormDefault="qualified">

	<xsd:element name="poiList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="poi" type="kcg:PointOfInterest"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="PointOfInterest">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="category" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="latitude" type="xsd:float" />
			<xsd:element name="longitude" type="xsd:float" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:integer" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== Letractively/kitcampusguide/tags/BA_Miclaus/2-3.PA_XML-Programmierung/poimanager/data/POIListTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<kcg:poiList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cm-tm.uni-karlsruhe.de/KCG POIList.xsd"
	xmlns:kcg="http://www.cm-tm.uni-karlsruhe.de/KCG">
	<kcg:poi id="2323">
		<kcg:name>Mensa am Adenaurerring</kcg:name>
		<kcg:latitude>49.011924</kcg:latitude>
		<kcg:longitude>8.41678</kcg:longitude>
	</kcg:poi>
	<kcg:poi id="12314">
		<kcg:name>Chemie Bibliothek</kcg:name>
		<kcg:latitude>49.01128</kcg:latitude>
		<kcg:longitude>8.413655</kcg:longitude>
	</kcg:poi>
	<kcg:poi id="1235">
		<kcg:name>Informatik Bibliothek</kcg:name>
		<kcg:latitude>49.013886</kcg:latitude>
		<kcg:longitude>8.419786</kcg:longitude>
	</kcg:poi>
</kcg:poiList>

=== Letractively/kitcampusguide/tags/BA_Miclaus/2-4.PA_Einbindung_von_Komponenten/poimanager/WebContent/WEB-INF/data/POIList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- xsd qualilfied, xml fully qualified -->
<kcg:poiList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:kcg="http://www.cm-tm.uni-karlsruhe.de/KCG" xsi:schemaLocation="http://www.cm-tm.uni-karlsruhe.de/KCG POIList.xsd ">
	<kcg:poi id="2323">
		<kcg:name>Mensa am Adenaurerring</kcg:name>
		<kcg:category>mensa</kcg:category>
		<kcg:latitude>49.011924</kcg:latitude>
		<kcg:longitude>8.41678</kcg:longitude>
	</kcg:poi>
	<kcg:poi id="12314">
		<kcg:name>Chemie Bibliothek</kcg:name>
		<kcg:category>bibliothek</kcg:category>
		<kcg:latitude>49.011280</kcg:latitude>
		<kcg:longitude>8.413655</kcg:longitude>
	</kcg:poi>
	<kcg:poi id="1235">
		<kcg:name>Informatik Bibliothek</kcg:name>
		<kcg:category>bibliothek</kcg:category>
		<kcg:latitude>49.013886</kcg:latitude>
		<kcg:longitude>8.419786</kcg:longitude>
	</kcg:poi>
</kcg:poiList>
